export const authConstant = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE'
}

export const freightConst = {
    FREIGHT_REQUEST: 'FREIGHT_REQUEST',
    FREIGHT_SUCCESS: 'FREIGHT_SUCCESS',
    FREIGHT_FAILURE: 'FREIGHT_FAILURE',
    ADD_FREIGHT_REQUEST: 'ADD_FREIGHT_REQUEST',
    ADD_FREIGHT_SUCCESS: 'ADD_FREIGHT_SUCCESS',
    ADD_FREIGHT_FAILURE: 'ADD_FREIGHT_FAILURE',
}

export const reqConst = {
    REQR_REQUEST: 'REQ_REQUEST',
    REQR_SUCCESS: 'REQ_SUCCESS',
    REQR_FAILURE: 'REQ_FAILURE',
    REQA_REQUEST: 'REQA_REQUEST',
    REQA_SUCCESS: 'REQA_SUCCESS',
    REQA_FAILURE: 'REQA_FAILURE',
    REQP_REQUEST: 'REQP_REQUEST',
    REQP_SUCCESS: 'REQP_SUCCESS',
    REQP_FAILURE: 'REQP_FAILURE',
    REQ_UPDATE_REQUEST: 'REQ_UPDATE_REQUEST',
    REQ_UPDATE_SUCCESS: 'REQ_UPDATE_SUCCESS',
    REQ_UPDATE_FAILURE: 'REQ_UPDATE_FAILURE',
    REQ_REJECT_REQUEST: 'REQ_REJECT_REQUEST',
    REQ_REJECT_SUCCESS: 'REQ_REJECT_SUCCESS',
    REQ_REJECT_FAILURE: 'REQ_REJECT_FAILURE'
}

export const orderConst = {
    ORDER_REQUEST: "ORDER_REQUEST",
    ORDER_SUCCESS: "ORDER_SUCCESS",
    ORDER_FAILURE: "ORDER_FAILURE",
    GET_ORDER_REQUEST: "GET_ORDER_REQUEST",
    GET_ORDER_SUCCESS: "GET_ORDER_SUCCESS",
    GET_ORDER_FAILURE: "GET_ORDER_FAILURE",
    UPDATE_ORDER_REQUEST: "UPDATE_ORDER_REQUEST",
    UPDATE_ORDER_SUCCESS: "UPDATE_ORDER_SUCCESS",
    UPDATE_ORDER_FAILURE: "UPDATE_ORDER_FAILURE",
    UPDATE_PRODUCT_REQUEST: "UPDATE_PRODUCT_REQUEST",
    UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
    UPDATE_PRODUCT_FAILURE: "UPDATE_PRODUCT_FAILURE",
}